# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server.models.imovel import Imovel  # noqa: F401,E501
from swagger_server import util


class InlineResponse200(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    def __init__(self, imoveis: List[Imovel]=None):  # noqa: E501
        """InlineResponse200 - a model defined in Swagger

        :param imoveis: The imoveis of this InlineResponse200.  # noqa: E501
        :type imoveis: List[Imovel]
        """
        self.swagger_types = {
            'imoveis': List[Imovel]
        }

        self.attribute_map = {
            'imoveis': 'imoveis'
        }

        self._imoveis = imoveis

    @classmethod
    def from_dict(cls, dikt) -> 'InlineResponse200':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The inline_response_200 of this InlineResponse200.  # noqa: E501
        :rtype: InlineResponse200
        """
        return util.deserialize_model(dikt, cls)

    @property
    def imoveis(self) -> List[Imovel]:
        """Gets the imoveis of this InlineResponse200.


        :return: The imoveis of this InlineResponse200.
        :rtype: List[Imovel]
        """
        return self._imoveis

    @imoveis.setter
    def imoveis(self, imoveis: List[Imovel]):
        """Sets the imoveis of this InlineResponse200.


        :param imoveis: The imoveis of this InlineResponse200.
        :type imoveis: List[Imovel]
        """

        self._imoveis = imoveis
