# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server.models.imobiliaria import Imobiliaria  # noqa: F401,E501
from swagger_server import util


class InlineResponse2001(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    def __init__(self, imobiliarias: List[Imobiliaria]=None):  # noqa: E501
        """InlineResponse2001 - a model defined in Swagger

        :param imobiliarias: The imobiliarias of this InlineResponse2001.  # noqa: E501
        :type imobiliarias: List[Imobiliaria]
        """
        self.swagger_types = {
            'imobiliarias': List[Imobiliaria]
        }

        self.attribute_map = {
            'imobiliarias': 'imobiliarias'
        }

        self._imobiliarias = imobiliarias

    @classmethod
    def from_dict(cls, dikt) -> 'InlineResponse2001':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The inline_response_200_1 of this InlineResponse2001.  # noqa: E501
        :rtype: InlineResponse2001
        """
        return util.deserialize_model(dikt, cls)

    @property
    def imobiliarias(self) -> List[Imobiliaria]:
        """Gets the imobiliarias of this InlineResponse2001.


        :return: The imobiliarias of this InlineResponse2001.
        :rtype: List[Imobiliaria]
        """
        return self._imobiliarias

    @imobiliarias.setter
    def imobiliarias(self, imobiliarias: List[Imobiliaria]):
        """Sets the imobiliarias of this InlineResponse2001.


        :param imobiliarias: The imobiliarias of this InlineResponse2001.
        :type imobiliarias: List[Imobiliaria]
        """

        self._imobiliarias = imobiliarias
